---
language: python
services:
  - docker
install:
  - pip install 'molecule<3' docker jmespath
script:
  - molecule --version
  - ansible --version
  - molecule lint
  - molecule syntax
  - molecule test
