---
- name: Install {{ __timesync_pkg }}
  package:
    name: "{{ __timesync_pkg }}"
    state: present

- name: Install other required packages
  package:
    name: "{{ required_packages }}"
    state: present
  when: required_packages is defined

- name: Gather package facts
  package_facts:
    manager: auto
