# SPDX-License-Identifier: MIT
---
dependency:
  name: galaxy
driver:
  name: ${LSR_MOLECULE_DRIVER:-docker}
platforms:
  - name: centos-8
    image: registry.centos.org/centos:8
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: /usr/lib/systemd/systemd --system
    capabilities:
      - SYS_TIME
provisioner:
  name: ansible
  log: true
  options:
    vv: true
  playbooks:
    converge: ../../tests/tests_default.yml
  env:
    ANSIBLE_STDOUT_CALLBACK: debug
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - check
    - destroy
